services:
    sabredav.collections.calendar:
        class: Sabre\CalDAV\CalendarRootNode
        arguments: ["@sabredav.backend.principal", "@sabredav.backend.caldav"]
        tags:
            -  { name: sabredav.collection }
