services:
    sabredav.collections.principal:
        class: Sabre\DAVACL\PrincipalCollection
        arguments: ["@sabredav.backend.principal"]
        tags:
            -  { name: sabredav.collection }
